/* Private comparison is loaded from the couple's configured sheet, never bundled. */
window.CondoHunting=(()=>{
  let data=[],loaded='',busy=false,error='',mode='comparison',filter='active',linkedSource='';
  const verdicts=['🤔 Not decided','👍 I like this one','❤️ Shortlist','💭 Maybe','👎 Pass'];
  const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const url=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:'';}catch{return '';}};
  function csv(text){const rows=[];let row=[],s='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){s+='"';i++;}else q=!q;}else if(!q&&(c===','||c==='\n')){row.push(s.replace(/\r$/,''));s='';if(c==='\n'){rows.push(row);row=[];}}else s+=c;}row.push(s.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);return rows;}
  function parse(text){const rows=csv(text);if(rows[0]?.[0]!=='Condo Hunting')throw Error('The sheet is not in the Condo Hunting column layout yet.');return rows[0].slice(1).map((name,i)=>{const o={name};rows.slice(1).forEach(r=>{if(r[0])o[r[0]]=r[i+1]||'';});o.id=o['Rental listing'];return o;}).filter(o=>o.name&&url(o.id));}
  const validId=id=>typeof id==='string'&&/^[\w-]{20,}$/.test(id);
  function sourceId(){const id=DB.get('condoSheet','');return validId(id)?id:(DB.get('condoCache',null)?.id||'');}
  function mergeSource(remote,local){const read=v=>{try{return JSON.parse(v);}catch{return '';}};const id=linkedSource||(validId(read(remote['cf-condoSheet']))?read(remote['cf-condoSheet']):read(local['cf-condoSheet']));return validId(id)?{...remote,'cf-condoSheet':JSON.stringify(id)}:remote;}
  function eligible(year,furnishing){const y=Number(year),t=String(furnishing||'');return Number.isInteger(y)&&y>=2022&&y<=new Date().getFullYear()&&/\bfully[ -]+furnished\b/i.test(t)&&!/(?:part(?:ly|ially)?[ -]+furnished|unfurnished|un-furnished|not[ -]+(?:fully[ -]+)?furnished|fully fitted|only .*rooms? furnished|basic unit|bare unit)/i.test(t);}
  function acceptLink(){const m=location.hash.match(/^#homes\?sheet=([\w-]{20,})$/);if(m){linkedSource=m[1];DB.set('condoSheet',m[1]);history.replaceState(null,'','#homes');}}
  async function refresh(){const id=sourceId();if(!/^[\w-]{20,}$/.test(id)||busy)return;busy=true;error='';render();try{const r=await fetch(`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/export?format=csv&gid=0`,{cache:'no-store'});if(!r.ok)throw Error('Sheet could not be loaded.');data=parse(await r.text());loaded=id;DB.set('condoCache',{id,data,at:Date.now()});}catch(err){error=err.message||'Could not refresh the comparison.';}finally{busy=false;render();}}
  function connect(){const value=document.getElementById('condo-connect').value.trim();const id=value.match(/\/d\/([\w-]+)/)?.[1]||value;if(!/^[\w-]{20,}$/.test(id)){error='Paste the Google Sheet link.';render();return;}DB.set('condoSheet',id);loaded='';data=[];refresh();}
  function votes(o){const v=DB.get('condoVotes',{})[o.id]||{};return {F:v.F??o['Fares verdict'],C:v.C??o['Charlotte verdict'],FS:v.FS??(o['Fares seen']==='TRUE'),CS:v.CS??(o['Charlotte seen']==='TRUE')};}
  function status(o,v){if(!eligible(o['Build year filter'],o.Furnishing))return 'Excluded — requires confirmed 2022+ completion and full furnishing';if(+o['Rent RM/month']>+(o['Budget ceiling RM']||5000))return 'Excluded — over budget';if(+o['Build year filter']<+(o['Minimum build year']||2022))return 'Excluded — built before 2022';if(+o['Size sqft']<+(o['Minimum size sqft']||800))return 'Excluded — too small';if(v.F===verdicts[2]&&v.C===verdicts[2])return '❤️ Both shortlist';if(v.F===verdicts[4]||v.C===verdicts[4])return 'Discuss concern';if(!v.FS||!v.CS)return 'Review first';return 'Await joint decision';}
  function vote(index,key,value){const o=data[index];if(!o)return;const all=DB.get('condoVotes',{});all[o.id]={...(all[o.id]||{}),[key]:value};DB.set('condoVotes',all);render();}
  const link=(v,label)=>url(v)?`<a href="${e(url(v))}" target="_blank" rel="noopener noreferrer">${e(label)}</a>`:'';
  const field=(o,key)=>o[key]?`<div class="ch-field"><h4>${e(key)}</h4><p>${e(o[key])}</p></div>`:'';
  function render(){const root=document.getElementById('condo-root');if(!root)return;window.CondoMap?.destroy();const legacy=document.getElementById('hm-legacy');legacy.hidden=mode!=='explore';root.hidden=mode==='explore';document.querySelectorAll('[data-condo-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.condoMode===mode));if(mode==='explore'){hmLegacyRender();return;}
    const id=sourceId();if(loaded!==id&&!busy){const cache=DB.get('condoCache',null);data=cache?.id===id?cache.data:[];loaded=id;if(id){refresh();return;}}
    if(!id){root.innerHTML=`<div class="ch-connect"><h3>Your shared comparison</h3><p>Open the private condo link shared in your chat to load the comparison automatically on this device. The connection syncs to your other signed-in devices. You can also paste the sheet link below.</p><label for="condo-connect">Google Sheet link</label><input id="condo-connect" type="url" placeholder="Paste the sheet link"><button class="btn primary" onclick="CondoHunting.connect()">Connect comparison</button><p role="status">${e(error)}</p></div>`;return;}
    const counts=data.filter(o=>!status(o,votes(o)).startsWith('Excluded')).length;
    const toolbar=`<div class="ch-toolbar"><div><strong>${counts} options · ${data.length-counts} excluded</strong><p>Fully furnished · completed 2022 or later. Unclear or conflicting claims are hidden.</p></div><button class="btn" onclick="CondoHunting.refresh()" ${busy?'disabled':''}>${busy?'Refreshing…':'Refresh sheet'}</button></div><div class="ch-filter" aria-label="Filter comparisons">${[['all','All qualifying'],['active','In criteria'],['shortlist','Our shortlist']].map(([k,n])=>`<button aria-pressed="${filter===k}" onclick="CondoHunting.filter('${k}')">${n}</button>`).join('')}</div><p class="ch-sync">Sheet details refresh here. App verdicts sync across signed-in phones; sheet votes stay separate. ${link(`https://docs.google.com/spreadsheets/d/${id}/edit`,'Open comparison sheet')}</p>${error?`<p class="ch-error" role="alert">${e(error)} ${data.length?'Showing the saved comparison.':'Check sheet sharing and try Refresh.'}</p>`:''}`;
    const entries=data.map((o,index)=>({o,index,v:votes(o),st:status(o,votes(o))})).filter(({o})=>eligible(o['Build year filter'],o.Furnishing)).filter(({st})=>filter==='active'?!st.startsWith('Excluded'):filter==='shortlist'?st==='❤️ Both shortlist':true);
    if(mode==='map'){root.innerHTML=toolbar+'<div id="condo-map-root"></div>';CondoMap.render(document.getElementById('condo-map-root'),entries,{vote,verdicts,details:index=>{mode='comparison';render();document.getElementById('ch-card-'+index)?.scrollIntoView({block:'start'});}});return;}
    root.innerHTML=toolbar+`<div class="ch-grid">${data.map((o,index)=>{
      const v=votes(o),st=status(o,v);if(!eligible(o['Build year filter'],o.Furnishing))return '';if(filter==='active'&&st.startsWith('Excluded')||filter==='shortlist'&&st!=='❤️ Both shortlist')return '';
      return `<article class="ch-card" id="ch-card-${index}"><div class="ch-heading"><span class="ch-area">${e(o.Neighbourhood)}</span><h3>${e(o.name)}</h3>${link(o.id,'View rental listing ↗')}</div>${url(o['Photo URL'])?`<a class="ch-photo" href="${e(url(o.id))}" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="${e(url(o['Photo URL']))}" alt="Listing photo of ${e(o.name)}" onerror="this.parentElement.innerHTML='Photo unavailable — view listing ↗'"></a>`:'<div class="ch-no-photo">Photo not retrieved — use the listing above</div>'}<div class="ch-body"><div class="ch-price">RM ${Number(o['Rent RM/month']).toLocaleString()}<small> / month</small></div><p class="ch-spec">${e(o['Size sqft'])} sqft · ${e(o['Size m²'])} m² · ${e(o.Bedrooms)} beds · ${e(o.Bathrooms)} baths</p><p class="ch-status ${st.startsWith('Excluded')?'excluded':st.includes('Both shortlist')?'shortlisted':''}">${e(st)}</p>${field(o,'Completion / VP')}<div class="ch-commute"><h4>Office → home, rush hour</h4><div><span>Leave 6 pm<strong>${e(o['CEVA → home · leave 6 pm'])}</strong></span><span>Leave 6:30 pm<strong>${e(o['CEVA → home · leave 6:30 pm'])}</strong></span></div><p>${e(o['Road km / route'])}</p><p>${e(o['Commute basis'])}</p>${link(o['Route · 6 pm'],'6 pm route')} · ${link(o['Route · 6:30 pm'],'6:30 pm route')}</div><div class="ch-votes">${[['F','Fares'],['C','Charlotte']].map(([k,n])=>`<div><label class="ch-seen"><input type="checkbox" ${v[k+'S']?'checked':''} onchange="CondoHunting.vote(${index},'${k}S',this.checked)">${n} seen</label><label class="ch-vlabel" for="ch-${index}-${k}">${n} verdict</label><select id="ch-${index}-${k}" onchange="CondoHunting.vote(${index},'${k}',this.value)">${verdicts.map(x=>`<option ${v[k]===x?'selected':''}>${e(x)}</option>`).join('')}</select></div>`).join('')}</div>${['Balcony / floor / view','Living room','Furnishing','Parking spaces','Next action / concerns','Gym equipment'].map(k=>field(o,k)).join('')}${link(o['Gym evidence photo'],'View gym evidence photo ↗')}${field(o,'Pool sunshine calculation')}${link(o['Facility plan'],'Open facility plan ↗')}${field(o,'Seasonal sun / shadow')}${field(o,'Sun method / limits')}${link('https://gml.noaa.gov/grad/solcalc/solareqns.PDF','Solar calculation method (NOAA)')}${field(o,'Walkability evidence')}<div class="ch-links">${[['Exact address / Maps','Address'],['Local shops / Maps','Local shops'],['Nearby mall / Maps','Nearby mall'],['Condo YouTube tour','Condo tour'],['Area YouTube tour','Area tour'],['Agent contact','Contact agent'],['Evidence / source','Source']].map(([k,n])=>link(o[k],n)).join('')}</div><p class="ch-sync">${e(o.Agent)} · ${e(o['Viewing stage'])}<br>Research checked ${e(o.Checked)}. Listing photos may show a staged or different unit; confirm before viewing.</p></div></article>`;
    }).join('')}</div>${!busy&&data.length===0?'<p>No listings loaded yet.</p>':''}`;
    if(filter==='shortlist'&&!data.some(o=>status(o,votes(o))==='❤️ Both shortlist'))root.insertAdjacentHTML('beforeend','<p class="ch-empty">Nothing shortlisted by both of you yet. Choose ❤️ Shortlist in both verdicts when you agree.</p>');
  }
  return {render,refresh,connect,vote,acceptLink,parse,eligible,sourceId,mergeSource,filter:k=>{filter=k;render();},mode:k=>{mode=k;render();}};
})();
