const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
const store={};const ctx={window:{},URL,Date,DB:{get:(k,d)=>store[k]??d,set:(k,v)=>store[k]=v},location:{hash:''},history:{replaceState(){}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/condo.js','utf8'),ctx);
const c=ctx.window.CondoHunting;
assert.equal(c.eligible(2022,'Fully furnished'),true);
for(const year of [2008,2021,null,'',2030])assert.equal(c.eligible(year,'Fully furnished'),false);
for(const text of ['','Furnished','Unfurnished','Partially furnished','Fully furnished / partially furnished','Header fully furnished; description fully fitted. Confirm furniture inventory.','Listed fully furnished; description specifies only two rooms furnished.'])assert.equal(c.eligible(2025,text),false,text);
assert.equal(c.eligible(2025,'Fully furnished per listing; confirm exact inventory.'),true);
const id='test_private_sheet_identifier_12345';store.condoCache={id,data:[]};assert.equal(c.sourceId(),id);
const incoming={'cf-condoSheet':'""','cf-films':'["preserve"]'};
const merged=c.mergeSource(incoming,{'cf-condoSheet':JSON.stringify(id)});
assert.equal(JSON.parse(merged['cf-condoSheet']),id);assert.equal(merged['cf-films'],incoming['cf-films']);
ctx.location.hash='#homes?sheet='+id;c.acceptLink();assert.equal(store.condoSheet,id);
const html=fs.readFileSync(root+'/index.html','utf8');
ctx.CondoHunting=c;ctx.hmAge=()=>null;
vm.runInContext(html.slice(html.indexOf('function hmPass('),html.indexOf('function hmBucket(')),ctx);
const f={beds:2,baths:2,size:800,rentMin:0,maxAge:1};
const base={src:'mine',builtYear:2022,title:'Fully furnished',rent:3500,beds:2,baths:2,size:900};
assert.equal(ctx.hmPass(base,f)&&ctx.hmAgeOk(base,f),true);
for(const l of [{...base,builtYear:2008},{...base,builtYear:null},{...base,title:'Partially furnished'}])assert.equal(ctx.hmPass(l,f)&&ctx.hmAgeOk(l,f),false);
console.log('PASS strict furnishing/year rules, manual listings, cache recovery and shared connection merge');
// Either person's Pass persists and suppresses other units in the same building.
const rejected={id:'https://example.com/a',name:'Test Residence · 900 sqft',Furnishing:'Fully furnished','Build year filter':2025,'Rent RM/month':3500,'Size sqft':900,'Fares verdict':'👎 Pass','Charlotte verdict':'💭 Maybe'};
assert.equal(c.status(rejected),'Archived — Pass');
assert.equal(c.status({...rejected,'Fares verdict':'💭 Maybe','Charlotte verdict':'👎 Pass'}),'Archived — Pass');
store.condoCache={id,data:[rejected]};
assert.equal(c.blockedDiscovery({title:'Fully furnished Test Residence 2 bedrooms'}),true);
assert.equal(c.blockedDiscovery({title:'Different condo',area:'Cheras'}),true);
assert.equal(c.blockedDiscovery({title:'Different condo',area:'Mont Kiara'}),false);
store.condoHistory={[rejected.id]:{o:rejected,building:'testresidence',reason:'Review decision'}};
assert.equal(c.status({...rejected,id:'https://example.com/new',name:'Test Residence · 1100 sqft','Fares verdict':'❤️ Shortlist','Charlotte verdict':'❤️ Shortlist'}),'Archived — Pass');
assert.match(c.status({...rejected,name:'Different place','Fares verdict':'💭 Maybe','Rent RM/month':6000}),/^Excluded — over budget/);
assert.equal(ctx.hmPass({...base,rent:5100},{...f,rentMax:4500}),false);
console.log('PASS either-person archive, building-level repeat suppression, Cheras and hard budget exclusion');
