const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
const ctx={window:{},URL,Map};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/condo-map.js','utf8'),ctx);
const m=ctx.window.CondoMap;
const p=o=>JSON.parse(JSON.stringify(m.coordinates(o)));
assert.deepEqual(p({'Map coordinates':'3.1, 101.2'}),[3.1,101.2]);
assert.equal(p({'Map coordinates':'92,101.2'}),null);
assert.equal(p({'Map coordinates':',101.2'}),null);
assert.equal(p({'Map coordinates':'NaN,101.2'}),null);
assert.equal(p({'Exact address / Maps':'https://maps.google.com/@3.123,101.456,12z'}),null);
assert.equal(p({'Route · 6 pm':'https://maps.google.com/dir/!1d100!2d2'}),null);
assert.deepEqual(p({'Route · 6 pm':'https://maps.google.com/dir/@1,2,12z/!1d100!2d2!1d101.2!2d3.1'}),[3.1,101.2]);
assert.deepEqual(p({'Exact address / Maps':'https://maps.google.com/?query=3.1%2C101.2'}),[3.1,101.2]);
const make=(name,coords,index)=>({o:{name,'Map coordinates':coords},index});
const result=m.group([make('Building A · unit 1','3.1,101.2',0),make('Building A · unit 2','3.1,101.2',1),make('Building B','3.2,101.3',2),make('Unmapped','',3)]);
assert.equal(result.groups.length,2);assert.equal(result.groups[0].entries.length,2);assert.equal(result.missing.length,1);
vm.runInContext(fs.readFileSync(root+'/condo.js','utf8'),ctx);
assert.equal(ctx.window.CondoHunting.parse('Condo Hunting,"A, place"\nRental listing,https://example.com/listing\nMap coordinates,"3.1, 101.2"')[0]['Map coordinates'],'3.1, 101.2');
console.log('PASS coordinate validation, route destination vs viewport/origin, grouped units, missing pins, CSV coordinate fields');
